export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// TODO: Spruce this up.  It's currently only used by the dynamic registration
// page, so not much is really needed.
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
