packages:
  - packages/**
  - apps/**
  - "!apps/gradebook/.next/**"
  - "!apps/agent/demo/**"
minimumReleaseAge: 0
minimumReleaseAgeExclude:
  - "@infonomic/*"
allowedDeprecatedVersions:
  abab: '2'
  domexception: '4'
sharedWorkspaceLockfile: true
allowBuilds:
  '@biomejs/biome': true
  '@contrast/fn-inspect': true
  '@datadog/pprof': false
  '@newrelic/fn-inspect': true
  '@newrelic/native-metrics': true
  '@parcel/watcher': true
  '@swc/core': true
  argon2: true
  bcrypt: true
  core-js: true
  cpu-features: false
  esbuild: true
  lightningcss-cli: true
  protobufjs: true
  sharp: true
  simple-git-hooks: true
  ssh2: false
