/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as CoursesRouteRouteImport } from './routes/_courses/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as CoursesCalculus2IndexRouteImport } from './routes/_courses/calculus-2/index'
import { Route as CoursesCalculus1IndexRouteImport } from './routes/_courses/calculus-1/index'
import { Route as CoursesCalculus1Lesson03RouteImport } from './routes/_courses/calculus-1/lesson-03'
import { Route as CoursesCalculus1Lesson02RouteImport } from './routes/_courses/calculus-1/lesson-02'
import { Route as CoursesCalculus1Lesson01RouteImport } from './routes/_courses/calculus-1/lesson-01'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRouteRoute = CoursesRouteRouteImport.update({
  id: '/_courses',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const CoursesCalculus2IndexRoute = CoursesCalculus2IndexRouteImport.update({
  id: '/calculus-2/',
  path: '/calculus-2/',
  getParentRoute: () => CoursesRouteRoute,
} as any)
const CoursesCalculus1IndexRoute = CoursesCalculus1IndexRouteImport.update({
  id: '/calculus-1/',
  path: '/calculus-1/',
  getParentRoute: () => CoursesRouteRoute,
} as any)
const CoursesCalculus1Lesson03Route =
  CoursesCalculus1Lesson03RouteImport.update({
    id: '/calculus-1/lesson-03',
    path: '/calculus-1/lesson-03',
    getParentRoute: () => CoursesRouteRoute,
  } as any)
const CoursesCalculus1Lesson02Route =
  CoursesCalculus1Lesson02RouteImport.update({
    id: '/calculus-1/lesson-02',
    path: '/calculus-1/lesson-02',
    getParentRoute: () => CoursesRouteRoute,
  } as any)
const CoursesCalculus1Lesson01Route =
  CoursesCalculus1Lesson01RouteImport.update({
    id: '/calculus-1/lesson-01',
    path: '/calculus-1/lesson-01',
    getParentRoute: () => CoursesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/calculus-1/lesson-01': typeof CoursesCalculus1Lesson01Route
  '/calculus-1/lesson-02': typeof CoursesCalculus1Lesson02Route
  '/calculus-1/lesson-03': typeof CoursesCalculus1Lesson03Route
  '/calculus-1/': typeof CoursesCalculus1IndexRoute
  '/calculus-2/': typeof CoursesCalculus2IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/calculus-1/lesson-01': typeof CoursesCalculus1Lesson01Route
  '/calculus-1/lesson-02': typeof CoursesCalculus1Lesson02Route
  '/calculus-1/lesson-03': typeof CoursesCalculus1Lesson03Route
  '/calculus-1': typeof CoursesCalculus1IndexRoute
  '/calculus-2': typeof CoursesCalculus2IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_courses': typeof CoursesRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_courses/calculus-1/lesson-01': typeof CoursesCalculus1Lesson01Route
  '/_courses/calculus-1/lesson-02': typeof CoursesCalculus1Lesson02Route
  '/_courses/calculus-1/lesson-03': typeof CoursesCalculus1Lesson03Route
  '/_courses/calculus-1/': typeof CoursesCalculus1IndexRoute
  '/_courses/calculus-2/': typeof CoursesCalculus2IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculus-1/lesson-01'
    | '/calculus-1/lesson-02'
    | '/calculus-1/lesson-03'
    | '/calculus-1/'
    | '/calculus-2/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculus-1/lesson-01'
    | '/calculus-1/lesson-02'
    | '/calculus-1/lesson-03'
    | '/calculus-1'
    | '/calculus-2'
  id:
    | '__root__'
    | '/_courses'
    | '/_public'
    | '/_public/'
    | '/_courses/calculus-1/lesson-01'
    | '/_courses/calculus-1/lesson-02'
    | '/_courses/calculus-1/lesson-03'
    | '/_courses/calculus-1/'
    | '/_courses/calculus-2/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CoursesRouteRoute: typeof CoursesRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_courses': {
      id: '/_courses'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CoursesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_courses/calculus-2/': {
      id: '/_courses/calculus-2/'
      path: '/calculus-2'
      fullPath: '/calculus-2/'
      preLoaderRoute: typeof CoursesCalculus2IndexRouteImport
      parentRoute: typeof CoursesRouteRoute
    }
    '/_courses/calculus-1/': {
      id: '/_courses/calculus-1/'
      path: '/calculus-1'
      fullPath: '/calculus-1/'
      preLoaderRoute: typeof CoursesCalculus1IndexRouteImport
      parentRoute: typeof CoursesRouteRoute
    }
    '/_courses/calculus-1/lesson-03': {
      id: '/_courses/calculus-1/lesson-03'
      path: '/calculus-1/lesson-03'
      fullPath: '/calculus-1/lesson-03'
      preLoaderRoute: typeof CoursesCalculus1Lesson03RouteImport
      parentRoute: typeof CoursesRouteRoute
    }
    '/_courses/calculus-1/lesson-02': {
      id: '/_courses/calculus-1/lesson-02'
      path: '/calculus-1/lesson-02'
      fullPath: '/calculus-1/lesson-02'
      preLoaderRoute: typeof CoursesCalculus1Lesson02RouteImport
      parentRoute: typeof CoursesRouteRoute
    }
    '/_courses/calculus-1/lesson-01': {
      id: '/_courses/calculus-1/lesson-01'
      path: '/calculus-1/lesson-01'
      fullPath: '/calculus-1/lesson-01'
      preLoaderRoute: typeof CoursesCalculus1Lesson01RouteImport
      parentRoute: typeof CoursesRouteRoute
    }
  }
}

interface CoursesRouteRouteChildren {
  CoursesCalculus1Lesson01Route: typeof CoursesCalculus1Lesson01Route
  CoursesCalculus1Lesson02Route: typeof CoursesCalculus1Lesson02Route
  CoursesCalculus1Lesson03Route: typeof CoursesCalculus1Lesson03Route
  CoursesCalculus1IndexRoute: typeof CoursesCalculus1IndexRoute
  CoursesCalculus2IndexRoute: typeof CoursesCalculus2IndexRoute
}

const CoursesRouteRouteChildren: CoursesRouteRouteChildren = {
  CoursesCalculus1Lesson01Route: CoursesCalculus1Lesson01Route,
  CoursesCalculus1Lesson02Route: CoursesCalculus1Lesson02Route,
  CoursesCalculus1Lesson03Route: CoursesCalculus1Lesson03Route,
  CoursesCalculus1IndexRoute: CoursesCalculus1IndexRoute,
  CoursesCalculus2IndexRoute: CoursesCalculus2IndexRoute,
}

const CoursesRouteRouteWithChildren = CoursesRouteRoute._addFileChildren(
  CoursesRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CoursesRouteRoute: CoursesRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
