-- NOTE: Run REINDEX on its own
REINDEX DATABASE modulus_dev;
ALTER DATABASE modulus_dev REFRESH COLLATION VERSION;
ALTER DATABASE modulus_dev REFRESH COLLATION VERSION;

-- NOTE: Run REINDEX on its own
REINDEX DATABASE postgres;
ALTER DATABASE postgres REFRESH COLLATION VERSION;
ALTER DATABASE postgres REFRESH COLLATION VERSION;
ALTER DATABASE template1 REFRESH COLLATION VERSION