# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Gradebook Deploy
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: 
      group: gradebook-deploy-group    # optional: ensure only one action runs at a time
      cancel-in-progress: true         # optional: cancel any in-progress jobs in the group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --wait-timeout 1000 --config fly-gradebook.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_GRADEBOOK_API_TOKEN }}
