import { faker } from '@faker-js/faker'
import type { NodePgDatabase } from 'drizzle-orm/node-postgres'
import { v7 as uuidv7 } from 'uuid'

import { userLogins, users } from '../schema/index.js'
import type * as schema from '../schema/index.js'

// IMPORTANT!!!! DO NOT CHANGE THE NUMBER OF MANUALLY CREATED
// USERS HERE. THERE SHOULD ALWAYS BE FIVE!!!! USER IDs AFTER
// FIVE GENERATED BY FAKER ARE AUTOMATICALLY ASSIGNED ROLES
export const seedUsers = async (db: NodePgDatabase<typeof schema>) => {
  const userData: (typeof schema.users.$inferInsert)[] = [
    {
      id: uuidv7(),
      email: 'anon@instructor.org',
      full_name: 'Anon Instructor',
      password:
        '$argon2id$v=19$m=65536,t=3,p=4$JpOLJrpSWIzdeuunZcLvYQ$Yb8DDTKxeq6s0cQn+3mhL/RjKT6Yv2iwYkEIH80ZdtU',
      is_email_verified: true,
      is_enabled: true,
    },
    {
      id: uuidv7(),
      email: 'anon@learner.org',
      full_name: 'Anon Learner',
      password:
        '$argon2id$v=19$m=65536,t=3,p=4$JpOLJrpSWIzdeuunZcLvYQ$Yb8DDTKxeq6s0cQn+3mhL/RjKT6Yv2iwYkEIH80ZdtU',
      is_email_verified: true,
      is_enabled: true,
    },
    {
      id: uuidv7(),
      email: 'alice@modulus.org',
      full_name: 'Alice',
      password:
        '$argon2id$v=19$m=65536,t=3,p=4$JpOLJrpSWIzdeuunZcLvYQ$Yb8DDTKxeq6s0cQn+3mhL/RjKT6Yv2iwYkEIH80ZdtU',
      is_email_verified: true,
      is_enabled: true,
    },
    {
      id: uuidv7(),
      email: 'bob@modulus.org',
      full_name: 'Bob',
      password:
        '$argon2id$v=19$m=65536,t=3,p=4$JpOLJrpSWIzdeuunZcLvYQ$Yb8DDTKxeq6s0cQn+3mhL/RjKT6Yv2iwYkEIH80ZdtU',
      is_email_verified: true,
      is_enabled: true,
    },
    {
      id: uuidv7(),
      email: 'carol@modulus.org',
      full_name: 'Carol',
      password:
        '$argon2id$v=19$m=65536,t=3,p=4$JpOLJrpSWIzdeuunZcLvYQ$Yb8DDTKxeq6s0cQn+3mhL/RjKT6Yv2iwYkEIH80ZdtU',
      is_email_verified: true,
      is_enabled: true,
    },
  ]

  const loginData: (typeof schema.userLogins.$inferInsert)[] = []

  const endTime = Date.now()
  const startTime = endTime - 1000 * 60 * 60 * 24 * 365
  const fakeUserCount = 5500

  for (let counter = 1; counter <= fakeUserCount; counter++) {
    const id = uuidv7()
    const creationTime = startTime + (endTime - startTime) * (counter / fakeUserCount) ** 2
    const creationDate = new Date(creationTime)

    const fakeLogin = (time: Date): typeof schema.userLogins.$inferInsert => ({
      time,
      user_id: id,
      provider: 'password',
      ip_address: faker.internet.ipv4(),
      outcome: faker.helpers.weightedArrayElement([
        { value: 'success', weight: 1000 },
        { value: 'failed_bad_password', weight: 10 },
        { value: 'failed_no_password', weight: 1 },
        { value: 'failed_disabled', weight: 1 },
      ] as const),
    })

    const logins = [
      // Initial login
      { ...fakeLogin(creationDate), outcome: 'success' as const },

      // Subsequent logins
      ...faker.date
        .betweens({
          from: creationTime + 1000 * 60 * 10,
          to: endTime,
          count: {
            min: 0, // Never logged in again.
            max: (endTime - creationTime) / (1000 * 60 * 60 * 24 * 2), // Avg. of twice per day
          },
        })
        .map(fakeLogin),
    ]

    const lastLoginSuccess = logins.reverse().find((l) => l.outcome === 'success')!

    userData.push({
      id,
      full_name: `${faker.person.firstName()} ${faker.person.lastName()}`,
      email: `${faker.number.int({ min: 1, max: 1000 })}_${faker.internet.email()}`,
      password:
        '$argon2id$v=19$m=65536,t=3,p=4$JpOLJrpSWIzdeuunZcLvYQ$Yb8DDTKxeq6s0cQn+3mhL/RjKT6Yv2iwYkEIH80ZdtU',
      created_at: creationDate,
      updated_at: creationDate,
      agreed_to_terms: true,
      last_provider: lastLoginSuccess.provider,
      last_login: lastLoginSuccess.time,
      last_login_ip: lastLoginSuccess.ip_address ?? '0.0.0.0',
      is_enabled: true,
      is_email_verified: true,
    })

    loginData.push(...logins)
  }

  console.log('Seed users start')

  const userIds: { id: string }[] = []
  let batchSize = 1000

  for (let i = 0; i < userData.length; i += batchSize) {
    const batch = userData.slice(i, i + batchSize)
    console.log(
      `Inserting user batch ${Math.floor(i / batchSize) + 1}/${Math.ceil(userData.length / batchSize)}`
    )
    const batchUserIds = await db.insert(users).values(batch).returning({ id: users.id })
    userIds.push(...batchUserIds)
  }

  console.log('Seed users done')

  console.log('Seed user_logins start')

  batchSize = 10000
  for (let i = 0; i < loginData.length; i += batchSize) {
    const batch = loginData.slice(i, i + batchSize)
    console.log(
      `Inserting user_login batch ${Math.floor(i / batchSize) + 1}/${Math.ceil(loginData.length / batchSize)}`
    )
    await db.insert(userLogins).values(batch)
  }

  console.log('Seed user_logins done')

  return userIds
}
